## Enable sudo
sudo:
  required

## Cache PIP installs across jobs
cache:
  - pip

## Select test language
language:
  python

## Select python version
python:
  - 3.4

## Prepare build environment
before_install:
  - ./scripts/configure-travis.sh

## Run automated tests using nose
script:
  - nosetests --where=tests --verbosity=3 --with-cov --cov eddy --cov-report term-missing --cov-config .coveragerc

# Report tests coverage
after_success:
  - coveralls