## Enable sudo
sudo:
  required

# Test on Trusty
dist:
  trusty

## Cache PIP installs across jobs
cache:
  - pip

## Select test language
language:
  python

## Select python version
python:
  - 3.4

## Test only master and dev branches
branches:
  only:
    - master
    - dev

## Prepare build environment
before_install:
  - ./scripts/configure-travis.sh

## Skip install step
install:
  true

## Start X Virtual Framebuffer
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5

## Run automated tests using nose
script:
  - nosetests --where=tests --verbosity=3 --with-cov --cov eddy --cov-report term-missing --cov-config .coveragerc

# Report tests coverage
after_success:
  - coveralls

# Setup notifications
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/aafeec4156a7fb26ef0c
    on_success: always  # options: [always|never|change] default: always
    on_failure: change  # options: [always|never|change] default: always
    on_start: never     # default: never