## Cache PIP installs across jobs
cache:
  - pip

## Select test language
language: python

## Select python version
python:
  - 3.5

# Jobs environment variables
env:
  matrix:
    - TEST=actions
    - TEST=datatypes
    - TEST=diagram
    - TEST=export
    - TEST=functions
    - TEST=palette
    - TEST=profiles
    - TEST=tools

## Test only master and dev branches
branches:
  only:
    - travis-ci

matrix:
  include:
  - os: linux
    language: python
    dist: trusty
    sudo: false
  - os: osx
    language: generic
    osx_image: xcode9.4

## Prepare build environment
#before_install:
# - ./scripts/configure-travis.sh

## Install dependencies from PyPI
install:
  - travis_retry pip install -U -r requirements/cython.txt
  - travis_retry pip install -U -r requirements/pyqt5.txt
  - travis_retry pip install -U -r requirements.txt
  - travis_retry pip install -U -r requirements-tests.txt
    
## Start X Virtual Framebuffer
#before_script:
#  - export DISPLAY=:99.0
#  - sh -e /etc/init.d/xvfb start
#  - sleep 5

## Run automated tests using nose
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then xvfb-run --server-args='-screen 0 1024x768x24' nosetests --tests=tests/test_${TEST}.py --verbosity=3 --with-cov --cov eddy --cov-report term-missing --cov-config .coveragerc; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then nosetests --tests=tests/test_${TEST}.py --verbosity=3 --with-cov --cov eddy --cov-report term-missing --cov-config .coveragerc; fi

# Report tests coverage
after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python setup.py bdist_archive --format=gztar --no-jre; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python setup.py bdist_dmg --no-jre; fi
#  - coveralls

# Setup notifications
#notifications:
#  webhooks:
#    urls:
#      - https://webhooks.gitter.im/e/aafeec4156a7fb26ef0c
#    on_success: always  # options: [always|never|change] default: always
#    on_failure: change  # options: [always|never|change] default: always
#    on_start: never     # default: never
